### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Pheanstalk\Exception\SocketException' with message 'Socket timed out!

### ISSUE THREAD

**Issue by tusharvr09** [pheanstalk/pheanstalk#180] opened 2018-10-08 06:33 UTC
After upgrading to the newer version of the pheanstalk package we encountered the below issue, i even tried downgrading it to v3.2.0 but still the issue persisted, it seems to work fine with v3.1.0 . The issue occurs when the worker is in idle state waiting for a job.

Below is trace for the issue -:

PHP Fatal error:  Uncaught exception 'Pheanstalk\Exception\SocketException' with message 'Socket timed out!' in /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:115
Stack trace:
#0 /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Connection.php(111): Pheanstalk\Socket\NativeSocket->getLine()
#1 /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Pheanstalk.php(398): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\ReserveCommand))
#2 /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Pheanstalk.php(281): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\ReserveCommand))
#3 /var/www/html/test/pheanstalk/run.php(25): Pheanstalk\Pheanstalk->reserve()
#4 /var/www/html/test/pheanstalk/run.php(42): Analytics_worker_process->get_data()
#5 {main}
  thrown in /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Socket/NativeSocket.php on line 115

Fatal error: Uncaught exception 'Pheanstalk\Exception\SocketException' with message 'Socket timed out!' in /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:115
Stack trace:
#0 /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Connection.php(111): Pheanstalk\Socket\NativeSocket->getLine()
#1 /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Pheanstalk.php(398): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\ReserveCommand))
#2 /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Pheanstalk.php(281): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\ReserveCommand))
#3 /var/www/html/test/pheanstalk/run.php(25): Pheanstalk\Pheanstalk->reserve()
#4 /var/www/html/test/pheanstalk/run.php(42): Analytics_worker_process->get_data()
#5 {main}
  thrown in /var/www/html/test/pheanstalk/vendor/pda/pheanstalk/src/Socket/NativeSocket.php on line 115

**Comment by SamMousa** [comment] 2018-10-08 06:40
The previous version had an issue where a dropped connection was never detected. I merged a fix that uses a timeout since a hard territory like you're getting is easier to deal with than an undetectable deadlock.

For now the solution is to increase the timeout and handle the exception by listening again.

**Comment by aripringle** [comment] 2018-10-08 21:48
What is the recommended implementation for this now? Once the exception is thrown and the socket closed, I'm not sure how to recover gracefully (without some PHP warnings), without re-instantiating Pheanstalk from scratch:

```
<?php

use Pheanstalk\Pheanstalk;
use Pheanstalk\Exception\SocketException;

ini_set('default_socket_timeout', 1); // For quick testing

require_once __DIR__ . '/../../vendor/autoload.php';

$pheanstalk = new Pheanstalk('beanstalkhost');
while (true) {
    try {
        $job = $pheanstalk->watch('testtube')->reserve();
    } catch (SocketException $e) {
        echo 'Caught exception: ' . $e->getMessage() . "\n";
    }
}
```

Results in:

```
Caught exception: Socket timed out!
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87

Warning: fwrite(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 87
```

If I try to disconnect the connection immediately after catching the exception, it does work, but the `fclose` that is called on the socket throws a warning (as the socket is fclose'd immediately before the exception is thrown):  https://github.com/pheanstalk/pheanstalk/blob/master/src/Socket/NativeSocket.php#L114

```
...
    } catch (SocketException $e) {
        echo 'Caught exception: ' . $e->getMessage() . "\n";
        $pheanstalk->getConnection()->disconnect();
    }
```

Results in:

```
Caught exception: Socket timed out!
PHP Warning:  fclose(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 93

Warning: fclose(): supplied resource is not a valid stream resource in .../vendor/pda/pheanstalk/src/Socket/StreamFunctions.php on line 93
```

**Comment by SamMousa** [comment] 2018-10-10 08:48
For now the solution is to increase the timeout and combine that with the renewal of the whole pheanstalk object.

I'm looking into several solutions, however these all come with some issues.

**Comment by SamMousa** [comment] 2018-10-10 09:15
Turns out errors on streams that do not pass any data along are really hard to detect.
Since no packets are being sent or received (the `reserve` command could take hours to complete) there's no reliable way to detect errors in the network. We're not receiving data but we don't know why, it might be an error it might not be.

I'm leaning towards the following solution:
1. Implement `reserve` using the old approach, meaning you as a user of the library have to take care of those kinds of errors and it might take a long time (if ever) for your runner to detect it's no longer connected and never going to receive more jobs.
2. Implement a listener that internally uses `reserve-with-timeout` repeatedly, effectively creating some data on the connection every 60 seconds or so.

This would create some overhead, but I doubt it'll be relevant in 99% of the cases.

Note that in case of `reserve` without timeout we could detect network events that happen on our host OS, but not on any hops in the network.

An alternative approach would be to use `SO_KEEPALIVE` on the stream, but this requires the stream extension. Although, upon further inspection it seems we use `stream_set_timeout` which means we're already depending on that extension to be available...

**Comment by SamMousa** [comment] 2018-10-10 15:54
@tusharvr09 @aripringle, in preparation for version 4 I have implemented wrappers for several socket implementations, one of them uses PHP's socket extension.
This gives us access to `SO_KEEPALIVE` which should allow for stable connections without tricky workarounds.

Would any of you be up for testing the master branch? If there's no feedback on the public API I'm okay with freezing it pretty soon in preparation for a v4 release.
Note that v4 does break backwards compatibility so it will require some changes in your code.

**Comment by aripringle** [comment] 2018-10-11 19:20
@SamMousa Great, thanks!

I've done some testing of the master branch on, just in a development environment, using the SocketSocket implementation. The worker I'm testing watches a tube, and for every job it reserves, it creates many new jobs in a different tube. All seems to work fine, and the code changes necessary were minimal (essentially just changing `new Pheanstalk` to `Pheanstalk::create`). I haven't had any timeout issues when waiting for a job to be reserved.

However, before I enabled the socket extension, it was defaulting to the StreamSocket implementation, which wasn't working for me at all. I'll open up a separate issue for it.

**Comment by exts** [comment] 2018-10-24 00:03
@SamMousa `renewal of the whole pheanstalk object.`

So creating a new instance of pheanstalk is the only solution? Also how close is 4.0? I wouldn't mind testing if this fixes the issue that's destroying my supervisord logs lol.

**Comment by SamMousa** [comment] 2018-10-24 05:14
Unfortunately yes, since the PR for the fix in 3 had been open for so long and the tests succeeded and it had positive feedback...
Alternatively go 1 minor version down.

4.0 is stable, I'm just waiting for other people to give me some feedback on the API changes.

**Comment by exts** [comment] 2018-10-24 06:36
Alright, I'll get 4.0 a shot

**Comment by tomsommer** [comment] 2018-10-24 09:33
In my mind this is a major breaking change, my `default_socket_timeout` is 30 and my workers are constantly dying with Exceptions after this change.

Why not allow the $timeout to be set in the object and have the default be either really high or indefinitely (to preserve BC). Having to adjust `default_socket_timeout` for pheanstalk alone makes no sense.

**Comment by dvaeversted** [comment] 2018-10-24 11:01
I agree with the possibility to set this timeout specific for Pheanstalk, i might have different requirements to how Pheanstalk acts.

And yes this took us quite by surprise, suddenly having workers fail after this update.

**Comment by SamMousa** [comment] 2018-10-24 12:04
@tomsommer I agree with you that this changes behavior, there are lots of discussions on this issue as to whether the change is an improvement.
In 3.1.* you will not be able to detect network interruptions meaning your worker might be stuck waiting while not realizing it will never receive another job.
Reasoning behind having the change was that long running worker would have some kind of process manager that restarts it when it crashes; thus this would result in filling peoples' logs, but not actually breaking their apps.

**Comment by SamMousa** [comment] 2018-10-24 12:10
Original underlying issue that I referred to can be found here: https://github.com/pheanstalk/pheanstalk/issues/13

**Comment by tomsommer** [comment] 2018-10-24 14:14
Right. But you are potentially making error handling go amok by throwing preciously unknown exceptions (that’s what happened to us), also the configuration on supervisord might not be configured to automatically restart the process.

**Comment by SamMousa** [comment] 2018-10-24 14:20
Hmm, `SocketException` was not previously unknown.

I realize you got bitten by this, and you're free to go back to 3.1.0. 
I have explained the reasoning motivating this change; with the current behavior you get an error that you can actually detect (which lead you here), with the old behavior you could end up in situations where you were not executing jobs but could not detect that all your workers were deadlocked...

If anything is unclear about the reasoning feel free to specify what and I'll try to provide more details. If everything is clear and you still feel that action should be taken, please elaborate on your proposed course of action.

**Comment by tomsommer** [comment] 2018-10-24 15:50
As I said, I think setting a default very-long timeout would be wise, not relying on `default_socket_timeout` to be the default (which it REALLY should not be).

You've solved an "issue" that has been left stale for 8 years, by breaking BC - I think the way people use Beanstalk nowadays have adapted to Reserve hanging indefinitely, and this is not default behaviour of this library anymore. perhaps gather inspiration from Perl and Python alternates?

**Comment by SamMousa** [comment] 2018-10-24 16:05
> As I said, I think setting a default very-long timeout would be wise, not relying on default_socket_timeout to be the default (which it REALLY should not be).

The problem is that a very long timeout will also result in not discovering broken connections for a very long time, exactly the issue we're trying to mitigate. 

Anyway, in your case staying on 3.1.x makes sense; apologies for any inconvenience caused. 
At least now you know that you're actively choosing to not discover broken connections and risk your workers becoming inactive.

**Comment by tomsommer** [comment] 2018-10-24 16:18
I know, my point was just that you are solving a non-problem (Issue was stale for 8 years), by breaking BC and introducing a new and perhaps even greater problem. But I understand that is your choice to make :)

**Comment by aktuba** [comment] 2018-11-07 10:13
https://github.com/pheanstalk/pheanstalk/pull/186

**Comment by SamMousa** [comment] 2018-12-03 10:14
I'm closing this issue.
Thanks for your comments @tomsommer; I'll take the things discussed into account for future releases!

Unrelated: please have a look at the v4 alpha release ;-)

**Closed by SamMousa** 2018-12-03 10:14 UTC

**Comment by Nevario** [comment] 2018-12-12 19:18
Happy I found this thread. I just lost a good 5 hours trying to figure out why every 2 minutes everything went to hell.

I've been running 3.0.2 in Production for the last 4 years and have never had an issue with a worker crashing. Maybe I just got lucky.

After tightening my composers version requirements and rolling back to 3.1, things seem good again.

**Comment by twmobius** [comment] 2018-12-17 13:12
@SamMousa Perhaps exposing the `_reconnect` private function would provide us with a workaround on the SocketException?

**Comment by SamMousa** [comment] 2018-12-17 13:13
No, the workaround is to recreate the instance.
It has almost no state and the state it has is not reliable after a connection error.

**Comment by twmobius** [comment] 2018-12-17 13:35
Well in my case the instance is created inside a factory, and then passed via other factories to controllers/services etc. Recreating the instance is easier said than done.

**Comment by SamMousa** [comment] 2018-12-17 13:54
Alternatively tighten your composer constraints and it'll work like before.

**Comment by GerMalaz** [comment] 2025-02-20 01:49
Too late to this party, but:

default_socket_timeout [int]
        Default timeout (in seconds) for socket based streams. Specifying a negative value means an infinite timeout.

The last second sentence is not respected:

```$timeout = ini_get('default_socket_timeout');``` 

```if (($data === false) && microtime(true) - $timer > $timeout) {```

Checking for ```$timeout >=0``` restores 3.1 behavior of waiting forever.
