### ISSUE TITLE
A question regarding the way socket reads message

### ISSUE THREAD

**Issue by yellow1912** [pheanstalk/pheanstalk#232] opened 2021-04-01 06:37 UTC
I have been using pheanstalk for a long time, it has been working flawlessly for me. Recently, I tried to use Swoole (coroutine extension for PHP) and I got into a timeout issue with pheanstalk:

https://github.com/swoole/swoole-src/issues/4092

This particular line causes the timeout:

`$result = socket_read($this->socket, $length - mb_strlen($buffer, '8BIT'));`

If I change it to the following code, then the issue is resolved:

`$result = socket_read($this->socket, $length - mb_strlen($buffer, '8BIT'), PHP_NORMAL_READ);`

I know it's not an issue caused by pheanstalk, but I don't know much about socket_read and I'm having trouble understanding why this caused an issue at all. If you happen to have any pointer to further debug this it will be greatly appreciated. For now, I just use the quick hack PHP_NORMAL_READ but I'm unsure if that may have other hidden issues.

**Comment by SamMousa** [comment] 2021-04-01 12:35
I'm closing this since it is not related to this library. The issue is caused by sharing sockets, you must not share sockets on a stateful connection, it will never work properly.

Note that your hack might randomly work in this case, but you will never get reliable results.

**Closed by SamMousa** 2021-04-01 12:35 UTC

**Comment by yellow1912** [comment] 2021-04-01 15:13
Thank you very much for the pointer, so sharing socket is an issue. By sharing socket, in this situation means the same instance of pheanstalk right?

Obviously you may not know the answer, and that is okie. But in case you know, do you think that if I use a single socket outside of any coroutine, then create a new coroutine for each job will solve that? With that approach I will have only 1 single coroutine, I will not have to share it? Or perhaps I got it all wrong and actually I should create new pheanstalk instance inside each coroutine to avoid sharing?
