### ISSUE TITLE
reserve(..) makes php scripts zombies

### ISSUE THREAD

**Issue by StevenFlecha** [pheanstalk/pheanstalk#216] opened 2020-05-03 05:33 UTC
Hi,

We recently upgraded from 3.2 to 4.01 and we had $beanstalkd->reserve(5) on many places on our code.

Our clusters suddenly started getting very unstable and every BE pod using Beanstalkd became Chromes munching like crazy on memory.

After a LOT of debugging  we found that reason was:
`$beanstalkd->reserve(5);`

This caused the queue workers to become zombies and eat memory. As php is not meant to keep running long time we have a setup that after x tasks / time the script is exited (killed) and then restarted. Because they became zombies they never exited but new ones were started so that added up.

Changing it to:
`$job = $pheanstalk->reserveWithTimeout(5);`

Fixed the issue. 

Its not really a bug but more of a backward compability improvement where if you pass argument with reserve(..) it should give an error if nothing is done with it as reserve(5) now just acts the same as reserve().

**Comment by SamMousa** [comment] 2020-05-03 06:25
This is clearly stated in the readme. Did you look at it before upgrading? If you feel it is lacking I'm open to improving docs..

**Comment by SamMousa** [comment] 2020-05-29 15:00
Closing this, people should not switch major versions without reading the upgrade notes first.

**Closed by SamMousa** 2020-05-29 15:00 UTC

**Comment by gopi-ar** [comment] 2020-07-31 10:41
@SamMousa this caught us by surprise too. We read your note before upgrading and luckily the underlying code as well! Since this is a pretty major change, and old installs will use `->reserve(<time>)`, I'd suggest adding this specific gotcha to the readme. Let me know if you want me to send a PR.

**Comment by SamMousa** [comment] 2020-07-31 10:42
Yes please!

**Comment by gopi-ar** [comment] 2020-07-31 11:03
Done! Could you tag a new release please? We need that for full 7.4 compatibility..

**Comment by SamMousa** [comment] 2020-07-31 11:12
I'm on mobile, could you check if it should be 4.1.0 or 4.0.x? I don't think we have new features although 7.4 compatibility could be considered a feature and not a bugfix

**Comment by gopi-ar** [comment] 2020-07-31 11:20
This one change to [build_phar.php](https://github.com/pheanstalk/pheanstalk/compare/v4.0.1...master#diff-5b11a670a80f1218f35b039e6d600bcbR24) fixed 7.4 compatibility :-). According to [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) anyway.

Latest release is `v4.0.1`. I'd say `4.0.2` since v4 was supposed to be compatible with 7.4 anyway and only a minor bug was fixed for full compatibility.

**Comment by SamMousa** [comment] 2020-07-31 11:27
Thanks :smile:

**Comment by gopi-ar** [comment] 2020-08-03 05:44
Thanks for the release @SamMousa ! Could you also push the update to packagist? Or maybe configure [webhooks](https://packagist.org/about#how-to-update-packages) to save you time in the future.

**Comment by SamMousa** [comment] 2020-08-03 06:33
It should be configured.. Maybe it didn't work. Will manually update from packagist now

**Comment by SamMousa** [comment] 2020-08-03 06:37
Ah I see, I don't have permission to the packagist parts, but I think anyone can update from the source repo. So I did that and packagist shows the version now.
